### ISSUE TITLE
Trying to get property 'idGenerator' of non-object

### ISSUE THREAD

**Issue by alex290** [pantera-digital/yii2-sberbank-pay#1]
Здравствуйте. Хотел использовать Ваше расширение yii2-sberbank-pay но при использовании вылезла такая ошибка
 
Trying to get property 'idGenerator' of non-object

Я так понимаю что в PHP 7.2 условие его определяет как объект а не переменню  if ($module->idGenerator) 
наверное надо заменить
if (!is_null(module->idGenerator))

**Comment by webmayak** [comment]
@alex290 благодарим за ваш issue! 👍 

Но дело немного в другом. Вы, видимо, использовали функционал вне контекста модуля, и соответственно $module был пустой, о чем и свидетельствует исключение.

С нашей стороны плохо что параметр 'idGenerator' модуля незадокументирован, этот момент поправим в #2

Если будут еще вопросы - пишите!

**Comment by maxneh** [comment]
Тоже столкнулся с такой же ошибкой, что можно сделать?

**Comment by webmayak** [comment]
@maxneh, благодарим! добавил дополнительную проверку в том месте, где возникает эта ошибка, пожалуйста, сделайте `composer update` и проверьте

также в [README.md](https://github.com/pantera-digital/yii2-sberbank-pay/blob/master/README.md#настройка-добавить-в-configmainphp) добавил описание к параметру idGenerator
