### ISSUE TITLE
Противоречие в указании типа свойства и правил обработки поля + типа поля в базе в модели Invoice.php

### ISSUE THREAD

**Issue by IljaPHP** [pantera-digital/yii2-sberbank-pay#10]
http://joxi.ru/12MpBJbSlJWdLm

**Comment by IljaPHP** [comment]
Забыли поменять после изменения типа поля, как видно по миграциям.

**Comment by webmayak** [comment]
@IljaPHP, спасибо, вы правы! 👍 поправим

**Comment by webmayak** [comment]
@IljaPHP, аннотацию поля `status` поправили, еще раз благодарим!

**Comment by IljaPHP** [comment]
> @IljaPHP, аннотацию поля `status` поправили, еще раз благодарим!

На доброе здоровье!
