### ISSUE TITLE
Ошибка с миграцией

### ISSUE THREAD

**Issue by sagittaracc** [pantera-digital/yii2-sberbank-pay#14]
После выполнения команды
```
php yii migrate --migrationPath=@pantera/yii2/pay/sberbank/migrations
```
Получаю ошибку:
```
Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [1049] Unknown database 'yii2advanced''
```
Понятно что этой базы у меня просто нет, но вопрос зачем вообще эта команда? Какая база эй нужна и где настраивать подключение к ней. У меня шаблон advanced.

Так же общий вопрос по системе оплаты через Сбербанк. Мне нужно внедрить в приложение оплату, но конкретно у меня не заключен договор со Сбербанком и логина и пароля у меня нет. Но у людей которые будут разворачивать - есть.
В связи с этим существует ли какой - то тестовый режим для проверки оплаты и что необходимо будет выполнить конечному потребителю? просто прописать логин api мерчента и пароль?

**Comment by webmayak** [comment]
@sagittaracc, Юрий, благодарим за ваше обращение

1. Для работоспособности модуля ему необходимо подключение к БД, чтобы создать таблицу `invoices` и работать с данными из неё.
2. Подключение к БД для advanced-приложения обычно настраивается в файле `common/config/main-local.php`
3. Для того, чтобы принимать оплату через Сбербанк собственнику сайта нужно заключить с банком договор интернет-эквайринга. При этом будут выданы логин и пароль к ТЕСТОВОМУ шлюзу. Оплаты при этом осуществляются с тестовых карт, которые приведены в документации эквайринга Сбербанка. После того как всё подключено и проверено на работоспособность, сотрудники Сбербанка высылают вам логин и пароль к БОЕВОМУ платежному шлюзу и уже можно принимать оплату по реальным картам.
