### ISSUE TITLE
Не срабатывает callback для генерации uniqid инвойса

### ISSUE THREAD

**Issue by adiafora** [pantera-digital/yii2-sberbank-pay#7]
Добрый день.
В callback idGenerator прописал правила для создания uniqid, но он не отрабатывает. Проверил, в models/Invoice->generateUniqid() на стр. 68 - `Module::getInstance()` всегда возвращает null, никогда не возвращает модуль. 
В других местах, где вызывается тот же Module::getInstance(), модуль возвращается успешно.
Причем если заменить `Module::getInstance()` на `Yii::$app->getModule('sberbank')`, то модуль возвращается и, соответственно, callback idGenerator отрабатывает. 
Вы с этим не сталкивались? Что может быть причиной?

Yii2 Advanced  2.0.34
PHP 7.2
Пробовал и на локальном ПК Windows 10 под OpenServer, и на хостинге под Linux

**Comment by webmayak** [comment]
@adiafora, да, вы правы, такое имеет место быть, при вызове `models/Invoice->generateUniqid()` вне контекста модуля

другими словами конструкция `Module::getInstance()` рассчитана именно на вызов в рамках модуля, такое мы используем для универсальности, чтобы можно было модуль называть не `sberbank`, а как-нибудь по-другому.. но это благое намерение почти никогда не находит применения на практике =)

PR принимаем, спасибо за инициативу и качественное описание проблемы! 👍
